#!groovy
import groovy.json.JsonSlurper
import java.nio.file.Paths

node {
    def env = System.getenv()
    def jsonSlourper = new JsonSlurper()
    stage ('Download') {
        checkout scm
        echo 'Yay!'
    }
    stage ('Setup') {
        bat 'npm run package-properties'
        def packageProperties
        Paths.get('package.json').withReader { reader ->
            packageProperties = slurper.parse(reader)
        }
    }
}