#!groovy
node {
    stage ('Download') {
        checkout scm
        echo 'Yay!'
    }
    stage ('Setup') {
        bat 'npm run package-properties'
        def packageProperties = readFile "/package-properties.txt"
    }
}